version: "3.9"

services:
  user-database:
    container_name: UserDatabase
    image: postgres
    ports:
      - "8091:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - /AFR-volume
    networks:
      - AFR

  announcement-database:
    container_name: AnnouncementDatabase
    image: postgres
    ports:
      - "8092:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - /AFR-volume
    networks:
      - AFR

  message-database:
    container_name: MessageDatabase
    image: postgres
    ports:
      - "8093:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - /AFR-volume
    networks:
      - AFR

  gateway:
    container_name: Gateway
    image: gateway-service.jar
    ports:
      - "8080:8080"
    volumes:
      - /AFR-volume
    networks:
      - AFR

  user:
    container_name: User
    image: user-service.jar
    ports:
      - "8081:8081"
    volumes:
      - /AFR-volume
    networks:
      - AFR

  announcement:
    container_name: Announcement
    image: announcement-service.jar
    ports:
      - "8082:8082"
    volumes:
      - /AFR-volume
    networks:
      - AFR

  message:
    container_name: Message
    image: message-service.jar
    ports:
      - "8083:8083"
    volumes:
      - /AFR-volume
    networks:
      - AFR

  zookeeper:
    container_name: Zookeeper
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - /AFR-volume
    networks:
      - AFR

  kafka:
    container_name: Kafka
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    volumes:
      - /AFR-volume
    networks:
      - AFR

volumes:
  AFR-volume:

networks:
  AFR:
    driver: bridge